#include "..\music.au3"
Local $x = PlayMusic("我想更加猥琐点")
ConsoleWrite($x & @CrLF)
Sleep(10000)
Local $x = PlayMusic("海阔天空 beyond")
ConsoleWrite($x & @CrLF)
Sleep(10000)
ConsoleWrite( PlayMusic("红豆 王菲")& @CrLF)
Sleep(10000)
PlayMusic("@50")
Sleep(3000)
ConsoleWrite( PlayMusic("小白杨 彭丽媛"))
Sleep(10000)
StopMusic()